### ISSUE TITLE
video-indexer-transcript.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#21] opened 2021-12-23 08:29 UTC
GRAMMAR ERROR PROBABLY DUE TO AUTO-TRANSLATION

Current Translation (If its  a translation issue):
alle potenziale dell'IA

Suggested Translation (if it’s a translation issue):
Il potenziale dell'IA

![video-indexer-transcript](https://user-images.githubusercontent.com/64255878/147211623-5d1452ec-810a-45d4-bd20-2741a5bf4eef.png)

**Comment by stonezy123** [comment] 2022-08-16 02:14
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment] 2022-09-20 05:43
As the https://dev.azure.com/ceapex/CEINTL/_workitems/edit/692498 comments,
Currently the texts reported are left in English a by design since the text are from the intro screen from the video file on the page. So unless the video is localized the text should be left in English.

so close this issue as won't fix.

**Closed by stonezy123** 2022-09-20 05:43 UTC
Labels: Acknowledge
