### ISSUE TITLE
video-indexer-view-menu.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#24] opened 2021-12-23 08:31 UTC
UNTRANSLATED TEXT - PLEASE CHECK IF THIS IS FINE OR NEED TO BE LOCALIZED

Current Translation (If its  a translation issue):
Move into Roles

Suggested Translation (if it’s a translation issue):
Passare ai ruoli

![video-indexer-view-menu](https://user-images.githubusercontent.com/64255878/147211955-8859ddc9-e962-43dd-bb16-a8c82fca5306.png)

**Comment by stonezy123** [comment] 2022-09-20 05:41
As the https://dev.azure.com/ceapex/CEINTL/_workitems/edit/692498 comments,
_Currently the texts reported are left in English a by design since the text are from the intro screen from the video file on the page. So unless the video is localized the text should be left in English._

so close this issue as won't fix.

**Closed by stonezy123** 2022-09-20 05:41 UTC
Labels: Acknowledge, InLocalization
